### ISSUE TITLE
Variable in script

### ISSUE THREAD

**Issue by staatsfeind32215** [hilios/jQuery.countdown#101]
Hello,

really great job and very easy to install. But I have a question. I was not able to use a variable date which is defined in .TPL file and comes from PHP File. I can show this variable date in the .tpl file as {$musiclist.user_date_contract}

How can I integrate this variabel into the script and replace '2015/01/01' :

  $('#getting-started').countdown('2015/01/01', function(event) {
    $(this).html(event.strftime('%w weeks %d days %H:%M:%S'));
  });

Thanks for your help

**Comment by hilios** [comment]
Just formats the date `{$musiclist.user_date_contract}` like `YYYY/MM/DD`, I think you should ask this  question at the PHP framework board, instead of here:

```js
$('#getting-started').countdown(<?= $musiclist.user_date_contract ?> // ...
```
