### ISSUE TITLE
TImezone Issue

### ISSUE THREAD

**Issue by asifsaho** [hilios/jQuery.countdown#103]
As I understand the countdown calculate from current user time to targeted time. Is there any way to make fixed the current time to a specific timezone?

My scenario is, the backend providing time as Berlin timezone when a user open it from a timezone ahead from Barlin and then sometimes users time ahead from from target time (because backend check next event by comparing with Barlin time stamp) as a result the timer got crashed.

**Comment by hilios** [comment]
Yes there is, you have to use [MomentJS](http://momentjs.com/) to generate the time with the correct offset (from the user point of view):

```js
var time = moment('The berlin hour here').utcOffset(1) // or .tz("Europe/Berlin");
$('#clock').countdown(time);
```

**Comment by CLGolden** [comment]
Hello. I'm totally new to jQuery and js, and this is exactly what I need to accomplish on a website. In other words, I need my audience to see the same remaining hours mins and secs no matter where they are in the world. I wonder if anyone would be willing to give a more complete example of how moment.js would be integrated with Final Countdown. 

Here is how I've set it up. 
`<div id="countdown-timer" style="font-size:30px; position:relative; left:285px; text-align:center;"></div>`

`<script type="text/javascript">`
`$('#cou ntdown-timer').countdown('2015/04/07 17:30:00', function(event) {
$(this).html(event.strftime('<div style="float:left; width:80px; padding:5px; border:1px solid #000; border-radius:5px; margin-right:10px; line-height:1;">%-D<br>day%!D</div> <div style="float:left; width:80px; padding:5px; border:1px solid #000; border-radius:5px; margin-right:10px; line-height:1;">%-H<br> hr%!H</div> <div style="float:left; width:80px; padding:5px; border:1px solid #000; border-radius:5px; margin-right:10px; line-height:1;">%M<br>min</div> <div style="float:left; width:80px; padding:5px; border:1px solid #000; border-radius:5px; margin-right:10px; line-height:1;">%S<br>sec</div>'));
  });`
`</script>`

From California, the offset would be UTC -8. 

Thanks for any help you all would be willing to give.

**Comment by samgavinio** [comment]
Momemnt works nicely since there currently is no server sync functionality. Thanks.

@CLGolden  Consider the following code:
```
var endDate = new Date('2015/04/07 17:30:00');
var timezoneAdjustedDate = moment(endDate.getTime()).utcOffset(-8).format('YYYY/MM/DD HH:mm:ss');
$('#countdown-timer').countdown(timezoneAdjustedDate, function(event) {
      //...
});

```

**Comment by samgavinio** [comment]
I've found that the best way to address the timezone difference issue as well as people messing with their OS time is to pass from the server the remaining time (something like the unix timestamp) rather than the desired end date. You then calculate in javascript the end date based on the current client time + the remaining time. This works because one second is the same regardless of where on earth you live. An example with a PHP based app would be:
```
        <?php $remainingTime = $targetDate->getTimestamp() - time(); ?>
        <input id="remainingTime" type="hidden" value='<?php echo $remainingTime?>'/>
```
```
        var remainingTimeMillisecond = $('#remainingTime').val() * 1000; //multiply by 1000 because               
                                                                                                                //javascript timestamps are in ms
        var currentTime = new Date();
        var endDate = new Date(currentTime.getTime() + remainingTimeMillisecond);
        $('#countdown-timer').countdown(endDate, fcuntion(event){
              //... 
        })
```

**Comment by hilios** [comment]
Here is a full implementation of the countdown timezone aware using Moment JS:
http://hilios.github.io/jQuery.countdown/examples/timezone-aware.html
