### ISSUE TITLE
Month Problem

### ISSUE THREAD

**Issue by mr-zenith** [hilios/jQuery.countdown#105]
I use your plugin and it shows 1 years and 22 month. As we know 22 month include one year.
Also frome now 2015/3/10 until 2017/01/12 is 1year and 10 months and 2 days not 22months
<script>
    $(document).ready(function () {
        $('#time').countdown('2017/01/12', function (event) {
            $(this).text(event.strftime('%Y %m %d'));
        });
    });
</script>

**Comment by hilios** [comment]
The months are not precise because some of then have 29 days, others 31 and so on. Check Issue #113

**Comment by Cristy94** [comment]
What's the solution for this?

I have a countdown from 1997 and it shows `22 years and 1140 weeks`, when weeks should be max `52`.
