### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by DiponRoy** [hilios/jQuery.countdown#108]
used finish.countdown, working fine https://jsfiddle.net/ayxphho2/
used only finish, not firing finished callback https://jsfiddle.net/ayxphho2/1/
![2015-03-30_1939](https://cloud.githubusercontent.com/assets/8077018/6897685/05da77ec-d717-11e4-919d-caba9d4fd2e8.png)

**Comment by hilios** [comment]
:+1:

**Comment by hilios** [comment]
Fixed!

**Comment by DiponRoy** [comment]
grt
