### ISSUE TITLE
Remove existing callbacks on countdown initialise

### ISSUE THREAD

**Issue by helloworlder** [hilios/jQuery.countdown#109]
Great plugin! I just think it would be safer if the existing function callbacks are removed when a timer is initialised on the same DOM element? 

In some use cases, countdowns may be re-initialized very often, sometimes with different callbacks. This will cause the call stack to grow with the callbacks exponentially until the page crashes.

I just think that removing existing callbacks during init would be a safer default behaviour?

**Comment by hilios** [comment]
Well, why the countdown would be initialised several times? It's not the plugin responsibility to manage the callbacks, it's of the developer. 

The plugin won't re-initialize the callback other than requested by code.
