### ISSUE TITLE
Is continuous (in loop) countdown is available? 

### ISSUE THREAD

**Issue by PrestaShark** [hilios/jQuery.countdown#110]
Hi,
I wonder is continuous (in loop) countdown is available with this script? 
Ex. we set the same daily time at monday to friday like 14:00PM
If the time is reached the countdown reset the time and count again until next day.

One exception is Saturday and Sunday.
So if we have Friday at  ex. 15:00PM the counter count remaining time to next Monday at 14:00PM

**Comment by hilios** [comment]
Work with the event `.on('finish.countdown', callback);` and just start again following your logic
