### ISSUE TITLE
Countdown doesnt count to other months

### ISSUE THREAD

**Issue by meivin123** [hilios/jQuery.countdown#113]
Hi,
the plugin isnt supporting month crossing countdowns without using weeks.
For Example today is the 2015-04-13 and I want to count down to 2015-05-15 and my code is:
```javascript
$('#timer').countdown("2015/05/15", function (event) {
        $(this).html(event.strftime('%d T - %H H - %M M'));
    });
```

The countdown shows: 03 T - 07 H - 29 M

**Comment by hilios** [comment]
There is a small difference between `%d` and `%D` as you can see at the [documentation](http://hilios.github.io/jQuery.countdown/documentation.html#formatter):

Directive | Description
------------|----------------
`%d` | Days left (taking away weeks)
`%D` | Total amount of days left
