### ISSUE TITLE
Countdown 1 hour

### ISSUE THREAD

**Issue by cosant** [hilios/jQuery.countdown#115]
Hello is possible to set the countdown time to 1 hour, if possible an example whould be great

Thank you

**Comment by hilios** [comment]
Yes, this is what the plugin is meant, I won't tailor an example for you but you can check: 
http://hilios.github.io/jQuery.countdown/examples.html

Or even check the source code
https://raw.githubusercontent.com/hilios/jQuery.countdown/gh-pages/examples/show-total-hours.md

With little effort and some search you can achieve what your want.
