### ISSUE TITLE
Package for meteor

### ISSUE THREAD

**Issue by suzurini** [hilios/jQuery.countdown#121]
Hello!
What is a meteor to use the package to not issue an error: "Expected tag name after` <`
... ss = "count curr top"> <% = curr%> </ span> "  ??? 
He does not like this syntax:" <% = ... => "

If you use {{curr}} instead of <% = curr%>, then everything works except "label.length <6? Label: label.substr (0, 3)" ...

How to display the label under the counter ??

And animated counter starts after updating the page ... Why?

Thanks!

**Comment by hilios** [comment]
This example was made using lodash template system, I don't know about metror syntax, but to adapt for it you should check how make the correct conversion....
