### ISSUE TITLE
Play / Stop / Pause buttons

### ISSUE THREAD

**Issue by devaris** [hilios/jQuery.countdown#122]
I am assigning the plugins events to let's say a play button:

$("#pause").click(function () {
        $('.timer').countdown('pause');
    });
$("#play").click(function () {
        $('.timer').countdown('resume');
});
$("#stop").click(function () {
        $('.timer').countdown('stop');
});

Once I click any of the above the rest do not work.

Can you please provide us with an ideal play/pause/stop button functioanlity?

Thank you

**Comment by hilios** [comment]
I have a working [example of this here](http://hilios.github.io/jQuery.countdown/examples/bootstrap.html)

You can check the source code in GH as well:
https://github.com/hilios/jQuery.countdown/blob/gh-pages/examples/bootstrapped.html#L109
