### ISSUE TITLE
How I can get the same style as the countdown in the home page

### ISSUE THREAD

**Issue by medBouzid** [hilios/jQuery.countdown#124]
Hi, I know that maybe it's not the ideal place to ask a such question, but I am just wondering how I can make the jquery countdown looks like the "black" one in your homepage http://hilios.github.io/jQuery.countdown/ 

I hope I can get some help from you.
Many Thanks.

**Comment by hilios** [comment]
This website is open-source as well at the `gh-pages` branch, check the source code at:
https://github.com/hilios/jQuery.countdown/blob/gh-pages/_includes/main-example.html
