### ISSUE TITLE
Incorrect number of days

### ISSUE THREAD

**Issue by djmtype** [hilios/jQuery.countdown#125]
Based on a countdown date, Sept. 25, 2015 from today, July 2, 2015. The months and hours display correctly. However, the amount of days return incorrectly. 
`%m` always returns `0` regardless of the countdown date.

For kicks, I tried `%M`. That returns `84` days, which is correct. It returns the total number of days until the event. 

However, I'm trying to display days left, taking the amount of months into consideration.

So, the countdown should read: 2 months, 22 days, 4 hours. How is it possible to render the countdown like that?

**Comment by djmtype** [comment]
I just realized, looking at your [home page](http://hilios.github.io/jQuery.countdown/), the number of days left until next year is off, too. It says 6 days. Shouldn't it be, ~26 days?

**Comment by hilios** [comment]
There is a gotcha with `days` and `totalDays` property, one is completely different then the other:

```
days:       '{int} Days left until next week',
totalDays:  '{int} Total amount of days left until final date',
```

**Comment by djmtype** [comment]
@hilios Thanks for the explanation of `days`. I previously came from using [http://keith-wood.name/countdown.html](http://keith-wood.name/countdown.html) so my understanding was somewhat askew. Meaning, if there were just under 70 total days left until the event, then the countdown would output `2 months, 9 days, 16 hours` left until the event. However, that doesn't seem to be the case with your plugin, right?

**Comment by hilios** [comment]
Yeah it would, just use the right format string:

```javascript
event.strftime('%m months %d days %-H hours left');
```

More about at the docs:
http://hilios.github.io/jQuery.countdown/documentation.html#formatter

**Comment by djmtype** [comment]
@hilios Thanks for your response, but by your logic `days: '{int} Days left until next week'` does not produce those results. According to the `days` implementation, there can only be 7 days max until the week restarts, and then it counts down from 7 again, correct? 

For example, today is July 16, 2015. An event that starts September 25, 2015 should equal `2 months, 8 days, 8 hours` from now. 

But, according to this plugin, using `event.strftime('%-m months %-d days %-H hours left');` the result is `2 months, 0 days, 8 hours`. In other words, there is a total of 70 days (`%D`) left until the event. 70 total days does not equal 2 months and 0 days. 

Do you understand what I'm trying to explain?

**Comment by hilios** [comment]
Your are bloody right my friend!!! The problem is how I calculate both _months_ and _years_, check-it out:

```js
{ //...
months    : Math.floor(this.totalSecsLeft / 60 / 60 / 24 / 30),
years     : Math.floor(this.totalSecsLeft / 60 / 60 / 24 / 365)
}
```

Can you see that not every month have 30 days, and neither years have always 365 days? I am very aware of this problem, and from day one I added a warning at the Formatter documentation, about it:

> * Due to their non linear constrains the years and months calculation are not precise and it's pretending to use as a approximation or not use at all.

Sorry about that, do you know how to do that calculation in the proper matter? I would be happy to implement or receive a pull request.

Regards!

**Comment by djmtype** [comment]
@hilios I'd love to help you out, but sadly, I'm just a mere CSS guy. Have you checked out [Keith Woods implementation](https://github.com/kbwood/countdown)?

**Comment by hilios** [comment]
In the end was very easy to implement, I did smalls improvements in the year and month calculation and added a new parameter to `strftime` and `event` object. 

Now you are able to get the amount of days left to the month (`%n`), like the following example:

```js
$('#clock').countdown('YYYY/MM/DD', function(event) {
    $(this).html(event.strftime('%m months and %n days till end.'));
});
```

Isn't always precise but, at least is something but either mr. Woods is.

You can grad the code at:
https://github.com/hilios/jQuery.countdown/blob/diff-dates/dist/jquery.countdown.js

Take a look to the unit test if you want to assure the implementation math:
https://github.com/hilios/jQuery.countdown/blob/diff-dates/test/unit/math_test.js#L23

**Comment by djmtype** [comment]
@hilios Thanks for your hard work, works like charm!

**Comment by hilios** [comment]
Ready to launch at version 2.1.0
