### ISSUE TITLE
Install problem - nothing displays

### ISSUE THREAD

**Issue by skratakh** [hilios/jQuery.countdown#126]
Hi I can't seem to get the script to work, does it only work with bower? i've even tried downloading local versions of the script and jquery and nothing i do seems to display anything at all. i've tried stripping everything out to a blank html page and just the example code and still nothing. what am i missing?

<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>

        <script src="js/jquery.countdown.min.js"></script>
        <script src="js/jquery-2.1.4.min.js"></script>
</head>

<body>
<div id="getting-started"></div>
<script type="text/javascript">
  $('#getting-started').countdown('2016/01/01', function(event) {
    $(this).html(event.strftime('%w weeks %d days %H:%M:%S'));
  });
</script>
</body>
</html>

**Comment by jonasboman** [comment]
jquery library should be inserted before the plug-in.
Do you get an error in initialization?

**Comment by hilios** [comment]
Yeah, the plugin need the jquery to work properly, so MUST appear after it...

```html
<script src="js/jquery-2.1.4.min.js"></script>
<script src="js/jquery.countdown.min.js"></script>
```

**Comment by skratakh** [comment]
Hi, i've tried with the jquery before the plug in and it still doesnt display anything, no error messages, nothing, it just doesn't appear. i have other jquery scripts running without any problems, i just cant get this one to even display.

**Comment by hilios** [comment]
I don't knwo what to do to help you, but I am pretty sure that is a problem within your HTML, because the plugin it's working:

https://github.com/hilios/jQuery.countdown/blob/gh-pages/_layouts/main.html#L17

**Comment by skratakh** [comment]
i think for now i'll leave it, i've wasted enough time trying to get it to work, thanks for your input anyway.

**Comment by jonasboman** [comment]
+1 
I've implemented a pure js function instead.

**Comment by tracethompson** [comment]
same thing here - nothing displays. No errors being thrown

**Comment by hilios** [comment]
Guys, please be specific I don't have a crystal ball, the plugin just loads fine at the examples and several others website, so show me examples!

**Comment by hilios** [comment]
Has I said, if you provide an example of how it's failing against your conditions let me know and we re-open this issue!
