### ISSUE TITLE
Timezone support?

### ISSUE THREAD

**Issue by Tasemu** [hilios/jQuery.countdown#127]
Hey guys, is there any timezone support at the moment for this? Much appreciated!

**Comment by rohitkhatri** [comment]
I don't think there is timezone support, looking for the timezone support, please add it.

**Comment by hilios** [comment]
Hello @Tasemu, I believe there is an example of timezone somewhere at the issues.

Here is the deal, there are specific libraries to handle the timezone issue like [Moment JS](http://momentjs.com/timezone/), this will never be a issue that **this** plugin will try to solve, but is pretty easy to integrate with the former suggestion.

**Comment by hilios** [comment]
Here is a full implementation of the countdown timezone aware using Moment JS:
http://hilios.github.io/jQuery.countdown/examples/timezone-aware.html

**Comment by fbonzon** [comment]
There is actually support for timezone already. One of the accepted input format of jQuery.countdown is milliseconds since epoch. Use this, instead of a date string. milliseconds since epoch are implicitly given in UTC timezone. Then it's up to the browser to convert into appropriate timezone.
