### ISSUE TITLE
Simple 10s countdown

### ISSUE THREAD

**Issue by gtonti** [hilios/jQuery.countdown#128]
I'm trying to use this JS to display a simple 10 seconds countdown, but I have no results (at least the timer starts at 60 (00) seconds).

this is my code:

<div class="counter">
	<? $start=date('j/n/Y h:i:s', strtotime("now")-10); ?>
	<div class="stat" data-countdown="<? echo $start; ?>"><span class="value">
	<script type="application/javascript">
		$('[data-countdown]').each(function() {
			var $this = $(this), finalDate = $(this).data('countdown');
			$this.countdown(finalDate, function(event) { $this.html(event.strftime('%S'));
			});
		});
	</script></span></div>
	</div>
	<hr />
	<div class="stat-info">secondi</div>
</div>

**Comment by hilios** [comment]
?
