### ISSUE TITLE
countdown is not a function.

### ISSUE THREAD

**Issue by jonasboman** [hilios/jQuery.countdown#129]
I've checked that jQuery is loaded (CDN) before countdown-plugin (status 200), but still I get the error message "countdown is not a function". I've tried loading plugin from CDN or locally.
I've even tried with a timeout - but no change. Even from the console it works.

Suggestions?

    function initPage() { 
            var _t1 = setTimeout(function () {
                $("#clock").countdown('2015/07/17', function (event) {
                    var $this = $(this).html(event.strftime('<td>%D:</td><td>%H:</td><td>%M</td>'));
                });
            }, 500);
        }

        $(function() {
            try{
                initPage();
            }
            catch (err) { console.log(err.message);}
        });

**Comment by hilios** [comment]
Probably you are loading the plugin before jQuery... but it's very hard to me to tell

**Comment by jonasboman** [comment]
Nope, like I said, jquery is loaded before the plugin.

**Comment by hilios** [comment]
Please be specific and show me examples where it's failing, the plugin just loads fine at the examples and several others website!
