### ISSUE TITLE
time is not paused

### ISSUE THREAD

**Issue by nseguel** [hilios/jQuery.countdown#131]
when the pause button is pressed, the counter stops, but see that nuavamente starts the counter, the time is as if he had never paused skips the number pause to the number that had been running.

**Comment by ferzegit** [comment]
Same bug. Can be viewed there:  http://hilios.github.io/jQuery.countdown/examples/bootstrap.html

**Comment by FagnerMartinsBrack** [comment]
This doesn't seems a bug. You can stop the timer at any specific moment to create a snapshot, but you can't stop time itself.

I believe the author should make clear the intent of the plugin:

1. "To map the real time as close as possible in the format of a counter, up to the target moment"
2. "To map a parallel time in the format of a counter, up to the target parallel moment"

I believe what you guys want is the second option.

**Comment by hilios** [comment]
Duplicated #116 

I will copy here the answer for that:

```js
var startDate = new Date(2015, 12, 24),
    pauseDate;

var $clock = $('#clock').countdown(startDate);

$('#btn-pause').click(function() {
    pauseDate = new Date();
});

$('#btn-resume').click(function() {
    var timedelta = new Date().getTime() - pauseDate.getTime(); // Elapsed time since the pause
    startDate = new Date(startDate.getTime() + timedelta);
    $clock.countdown(startDate);
});
```

Tks @FagnerMartinsBrack for the explanation!
