### ISSUE TITLE
Count up?

### ISSUE THREAD

**Issue by aakraak** [hilios/jQuery.countdown#134]
Is there a simple way to rewrite the code so it will count up?

**Comment by hilios** [comment]
Just set a config object `{elapse: true}` as the plugin functions second argument.

```js
$('#clock').countdown(fiveSeconds).on('update.countdown', function(event) {
  var $this = $(this);
  if (event.elapsed) {
    $this.html(event.strftime('After end: <span>%H:%M:%S</span>'));
  } else {
    $this.html(event.strftime('To end: <span>%H:%M:%S</span>'));
  }
});
```

Checkout the working example at the site: http://hilios.github.io/jQuery.countdown/examples/count-up.html

**Comment by onskyD** [comment]
`var elapse = $elapse;
var element = $('.lead-detail__counts');
var template = element.data('template');
var time = new Date(element.data('date') * 1000);
if (elapse){
    var finishDate = new Date().getTime();
} else {
    var finishDate = time.getFullYear() + '/' + (time.getMonth() + 1) + '/' + time.getDate();
}

element.countdown(finishDate, {
    elapse: elapse
}).on('update.countdown', function(event) {
    if (event.elapsed){
        var offset = getDateOffset((event.timeStamp - time) / 1000);
        var result = template;
        result = result.replace('%D', offset.days);
        result = result.replace('%H', offset.hours);
        result = result.replace('%M', offset.minutes);
        result = result.replace('%S', offset.seconds);
        element.html(result);
        // <div class="lead-detail__count">%D</div><div class="lead-detail__count">%H</div><div class="lead-detail__count">%M</div><div class="lead-detail__count">%S</div>
    } else {
        element.html(event.strftime(template));
    }
});

function getDateOffset(timeStamp){
    var seconds = parseInt(timeStamp, 10);

    var days = Math.floor(seconds / (3600 * 24));
    seconds  -= days * 3600 * 24;
    var hours   = Math.floor(seconds / 3600);
    seconds  -= hours * 3600;
    var minutes = Math.floor(seconds / 60);
    seconds  -= minutes * 60;

    return {
        days: days,
        hours: hours,
        minutes: minutes,
        seconds: seconds
    }
}`

**Comment by onskyD** [comment]
`var elapse = true;`
`var element = $('.lead-detail__counts');`
var template = element.data('template');
var time = new Date(element.data('date') * 1000);
if (elapse){
    var finishDate = new Date().getTime();
} else {
    var finishDate = time.getFullYear() + '/' + (time.getMonth() + 1) + '/' + time.getDate();
}

**Comment by onskyD** [comment]
https://gist.github.com/onskyD/cc7547b8c536f58ea3e1d61ce6dadc2c#file-scripts-js
