### ISSUE TITLE
Take start date completely out of consideration

### ISSUE THREAD

**Issue by digitalprecision** [hilios/jQuery.countdown#138]
Rather than deal with the timezone mess at the app layer, I have written the logic to be handled at the database layer. Basically what I am doing is calculating the time diff between two dates (both utc), and want to return the results to your countdown timer. 

Example: 3h 31m 9s between date_time_now and date_time_future (as calculated in query).

So I tried passing these static values to your api, but the timer doesn't countdown.

    // Ajax call populates data.payload (the query that does the actual diff calculation)

    // Arbitrary date, I just want to countdown 
    \$('#blast-again-countdown').countdown('2727-11-03', function(event) {

        $(this).html(event.strftime(data.payload.remaining_days + ' day ' + data.payload.remaining_hours + ' hr ' + data.payload.remaining_minutes + ' min %S sec'));
    });

Is it possible to disregard date, and just manually set the offsets?

**Comment by digitalprecision** [comment]
I was able to accomplish my goal by adding in momentjs so I can add the offsets to computer time. As mentioned earlier this is a huge benefit because now the user's local timezone is a non-issue.

    var targetDate = moment()
        .add(data.payload.remaining_days, 'day')
        .add(data.payload.remaining_hours, 'hour')
        .add(data.payload.remaining_minutes, 'minute')
        .add(data.payload.remaining_seconds, 'second')
        .format('YYYY-MM-DD HH:mm:ss');

**Comment by hilios** [comment]
Good to hear that you accomplished your goal, the I just feel that the plugin is a overhead to your code, Why didn't you use a `setInterval` directly, like:

 ```js
var countdown = setInterval(function() {
  var targetDate = moment()
    .add(data.payload.remaining_days, 'day')
    .add(data.payload.remaining_hours, 'hour')
    .add(data.payload.remaining_minutes, 'minute')
    .add(data.payload.remaining_seconds, 'second')
    .format('YYYY-MM-DD HH:mm:ss');
}, 300);
```
