### ISSUE TITLE
Redirect after countdown ends?

### ISSUE THREAD

**Issue by arillera** [hilios/jQuery.countdown#141]
Is it possible to redirect after the countdown ends? Similar to the way this countdown timer has as a callback feature http://keith-wood.name/countdown.html

Any feedback is appreciated and thanks for the awesome plugin!

**Comment by hilios** [comment]
Did you read the docs? 
http://hilios.github.io/jQuery.countdown/documentation.html#events

```js
$('#clock').countdown('YYYY/MM/DD').on('countdown.finish', function(event) {
    // Do the redirect!
});
```

**Comment by arillera** [comment]
Thanks did not see that in the docs, appreciate the help and great plugin!
