### ISSUE TITLE
Start issue

### ISSUE THREAD

**Issue by danametuka** [hilios/jQuery.countdown#142]
When i stop the countdown and start it again with

$('div#clock').countdown('stop');
$('div#clock').countdown('start');

The countdown starts as if it wasn't stopped (e.g. the count didn't stop)

see here
http://www.imk.co.il/countdown/

**Comment by hilios** [comment]
Duplicated from #116 and #131 

The count won't stop because it is physically impossible to stop **time** itself!!! At the issue #131 there is an snippet to achieve what you want!
