### ISSUE TITLE
Pause functionality - date object doesn't update / confusion what the intent of pausing does

### ISSUE THREAD

**Issue by bradmartin** [hilios/jQuery.countdown#144]
I think the naming of 'Pause' and 'Resume' are not accurate with the current functionality of the plugin.

In the bootstrap example, when you pause the interface "pauses" but since the date object doesn't get updated on "resume" the countdown isn't technically pausing so to speak.

If that doesn't make sense I'll explain further, maybe it's fulfilling what it is intended but some clarification on what the pause event does and doesn't do would be good. I couldn't find anything.

I'm using this in an Angular app and I'm currently working to update the date depending on time difference since it was paused but it feels too much like a hack of what is a simple and great plugin. :)

**Comment by hilios** [comment]
Duplicated from #116 and #131. The count won't stop because it is physically impossible to stop time itself!!!

There is a lot of explanation why it was implemented this way at the linked issues that you can read. But here is a little snippet to achieve the desired functionality:

```js
var startDate = new Date(2015, 12, 24),
    pauseDate;

var $clock = $('#clock').countdown(startDate);

$('#btn-pause').click(function() {
    pauseDate = new Date();
});

$('#btn-resume').click(function() {
    var timedelta = new Date().getTime() - pauseDate.getTime(); // Elapsed time since the pause
    startDate = new Date(startDate.getTime() + timedelta);
    $clock.countdown(startDate);
});
```
