### ISSUE TITLE
How to integrate the code ?

### ISSUE THREAD

**Issue by Inkoming** [hilios/jQuery.countdown#148]
Your plugin is very powerful but for some begginers that's not easy...

I have this not working:

ERROR:
#####################

[Error] TypeError: undefined is not a function (evaluating '$('div#clock').countdown')
	global code (index.php, line 780)

HTLM:
#####################

```html
<div class="kountdown">
<div id="clock"><strong>Some text...</strong></div>
</div>
```

SCRIPT:
#####################

```javascript
$('div#clock').countdown('2020/10/10', function(event) {
  var $this = $(this).html(event.strftime(''
    + '<span>%w</span> weeks '
    + '<span>%d</span> days '
    + '<span>%H</span> hr '
    + '<span>%M</span> min '
    + '<span>%S</span> sec'));
});
```

**Comment by hilios** [comment]
Probably because you didn't imported the code correctly in your HTML file.
