### ISSUE TITLE
NaN on chrome/canary

### ISSUE THREAD

**Issue by snavaneeth78** [hilios/jQuery.countdown#149]
Returns NaN on chrome. 
And the official  site (http://hilios.github.io/jQuery.countdown/) have a scary glitch.

my code below:
$(".countdown-container").countdown('23/9/2015', function(event) {
  $(this).html(event.strftime(
    '<div id="hours" class="contdown-span">%-H<span>hours</span></div>' +
    '<div id="minutes" class="contdown-span">%-M<span>minutes</span></div>' +
    '<div id="seconds" class="contdown-span">%-S<span>seconds</span></div>'
  ));
});
![ooo](https://cloud.githubusercontent.com/assets/9249861/10024677/e84be266-618a-11e5-8abc-bc39344f9ebe.jpg)

**Comment by snavaneeth78** [comment]
Found the solution. 

Chrome only accept this time format "yyyy/mm/dd".

**Comment by hilios** [comment]
The issue #100 explains the glitch further, but in few lines it is not an plugin issue, but a hardware acceleration problem :pensive:.

The allowed date formats are:

- YYYY/MM/DD
- MM/DD/YYYY
- YYYY/MM/DD hh:mm:ss
- MM/DD/YYYY hh:mm:ss

http://hilios.github.io/jQuery.countdown/documentation.html#introduction
