### ISSUE TITLE
How to restart the timer when it runs out?

### ISSUE THREAD

**Issue by ffejwright** [hilios/jQuery.countdown#155]
How do I restart the timer when it runs out, as opposed to having it count up? I have it set up for 48 hours, and want it to go back to 48 when it hits zero. Any ideas? Thanks in advance!

var twoDays = new Date().getTime() + 172800000;
$('#clock').countdown(twoDays, {elapse: true})
    .on('update.countdown', function(event) {
    var $this = $(this);
    var totalHours = event.offset.totalDays * 24 + event.offset.hours;
    if (event.elapsed) {
        // Restart here? 
    } else {
        $this.html(event.strftime(totalHours + ':%M:%S'));
    }
});

**Comment by hilios** [comment]
Use the [finish.countdown](http://hilios.github.io/jQuery.countdown/documentation.html#events) and then [restart the countdown](http://hilios.github.io/jQuery.countdown/documentation.html#controls).

**Comment by teclaelvis01** [comment]
an example?

**Comment by hilios** [comment]
@teclaelvis01 just click the second link at my comment.

**Comment by Pixelous** [comment]
@hilios I am trying to achieve this for several hours but no luck :(

Can you please give an example?

My code:

`var $clock = $( '#clock' );
	if ($clock.length) {
		var twoDays = new Date().getTime() + 2800;
		$clock.countdown(twoDays, {elapse: true})
		.on('update.countdown', function(event) {
			var $this = $(this);
			var totalHours = event.offset.totalDays * 24 + event.offset.hours;
			if (event.elapsed) {
				$this.countdown(twoDays, {elapse: true})
				.on('finish.countdown', function(event) {
					$this.countdown('start');
				});
			} else {
				$this.html(event.strftime(totalHours + ':%M:%S'));
			}
		});
	}`

**Comment by XuCcc** [comment]
i began to learn javascript....i try it bud it does't work....

```javascript
<script type="text/javascript">
  var twoDays = new Date().getTime() + 2800;
  $("#nextround")
    .countdown(twoDays)
    .on('update.countdown', function (event) {
      $(this).text(
        event.strftime('%H:%M:%S')
      );
    })
    .on('finish.countdown', function (event) {
      $("#nextround").countdown('resume');
    });
</script>
```
