### ISSUE TITLE
How to get current time from server.

### ISSUE THREAD

**Issue by jensej** [hilios/jQuery.countdown#161]
How to get current time from server, not from user?
It is possible?
I'm trying somethink like this, but its not working.
`var $clock = $(czasek).countdown(finaldate).on('update.countdown', function(event) { 

                if(event.elapsed == false)
                  {
                    $(this).html(event.strftime('%H:%M:%S'));    
                  }
                  else
                  {
                    $(this).html('End');
                  }

              });
                // Sync with the server time
                $.get("http://mysite.pl/site/time", {userMachineDate: new Date()}, function(data) {
                    var serverTimeOffset = new Date(data);
                    $clock.countdown(serverTimeOffset);
                    console.log('1a');
                });`

**Comment by hilios** [comment]
If the server-side is ok it should work. Please provide more info about the problem to have a proper feedback.

**Comment by jensej** [comment]
I trying like this:
 ` $(czasek).countdown(data_zbazy, function(event) {
                  $(this).html(event.strftime(' %H:%M:%S'));
                }, '<?= $now->format("M j, Y H:i:s O") ?>');
             
                });`
It's works but I compared result from PC with result from tablet and is the difference of 4 seconds.
With phone diffrence is 1 sec. It is any possible to correct it?

**Comment by hilios** [comment]
You could add the response time at the initialization.
