### ISSUE TITLE
Changing the day

### ISSUE THREAD

**Issue by WalibiBoy** [hilios/jQuery.countdown#162]
How can I change the day, that it has to count down to?

**Comment by hilios** [comment]
Sorry but I didn't understood your question? You mean, initialise the date? Please be more clear about what you're trying to accomplish

**Comment by dqmmpb** [comment]
Maybe I have the same question.
I want to count down from 2015-11-30 to 2015-11-10, not from 2015-11-30 to now. The 'now' time is a client new Date(). I want use a server time initialise this time.

**Comment by hilios** [comment]
Because of the internals of the plugins we cannot support this method, it would be inefficient and cause more harm than good. Sorry
