### ISSUE TITLE
Stop/Resume does not work correctly

### ISSUE THREAD

**Issue by diegojromerolopez** [hilios/jQuery.countdown#165]
Hello hilios

Resume action does not continue the countdown from the same point it was stopped. It should continue from the point it has been stopped (like a stopwatch).

In your own example [Bootstrap example](http://hilios.github.io/jQuery.countdown/examples/bootstrapped.html) can be seen the error. Click "Pause", wait 5 seconds and click "Start". Time should resume the countdown from the point it was but countdown decreases to actual countdown as if stop button was not clicked.

Am I missing something or this is an error?

Thank you.

**Comment by hilios** [comment]
Duplicated from #116, #131 and #144. 

TL; DR: The count won't stop because it is physically impossible to stop time itself!!!
