### ISSUE TITLE
How to exclude weekends 

### ISSUE THREAD

**Issue by sektorseven** [hilios/jQuery.countdown#166]
Hi, I need some help...

Is there a way to exclude weekends from the finalDate?

I am currently using the "Advanced Coupon Site" example and would like to exclude weekends from the countdown.

**Comment by hilios** [comment]
You don't wanna show it or you want to remove from the final date?

**Comment by sektorseven** [comment]
I don't want to show those days in the countdown.

I am building a holiday countdown to show people how many business days are left until a holiday.

**Comment by hilios** [comment]
http://hilios.github.io/jQuery.countdown/documentation.html#formatter

**Comment by seritpt** [comment]
I think it's not what he wants.
What I understand he wants is to not count the weekends.
I'm also developing a script with countdown too but I need not to count holidays, weekends and to countdown only beetween 9AM and 7PM hours.
In resume, to countdownd only on business days and hours beetween 9AM and 7PM hours.
It's important for SLA system to not countdown weekends and not businees days.
For example my team works beetween 9AM and 7PM and SLA with 48 hours of assistence must only countdown business open hours.
