### ISSUE TITLE
I need to give warning 10 seconds before the counter ends

### ISSUE THREAD

**Issue by abiramasenthil** [hilios/jQuery.countdown#170]

**Comment by hilios** [comment]
How about to use countdown.update and event.offset property (http://hilios.github.io/jQuery.countdown/documentation.html#events).

I believe that what you are trying to achieve is very similar to the Advanced example:
http://hilios.github.io/jQuery.countdown/examples/advanced-coupon-site.html

Just use the same approach to change the output or even create a new HTML.

Cheers
