### ISSUE TITLE
Pause is not actually pauses the counter. the counter still running and resume picks from their

### ISSUE THREAD

**Issue by abiramasenthil** [hilios/jQuery.countdown#171]
You have already mentioned we cannot pause the counter physically..
can we get the counter time in 'pause' and start counter with that time in resume?
If yes, How can I caught the counter time when it is paused?

**Comment by abiramasenthil** [comment]
I am using <span id="clock"></span> to display the counter

**Comment by hilios** [comment]
How about to use `countdown.update` and `event.offset` property (http://hilios.github.io/jQuery.countdown/documentation.html#events).

I believe that what you are trying to achieve is very similar to the Advanced example:
http://hilios.github.io/jQuery.countdown/examples/advanced-coupon-site.html

Just use the same approach to change the output or even create a new HTML.

Cheers

**Comment by abiramasenthil** [comment]
Hi Hillios,
I am not clear with setting a flag..
This is how I have started my countdown

function onSuccess(data) {
                milliSeconds = new Date().getTime() + data.d;
               
                $('#clock').countdown(milliSeconds, function(event) {
                    var totalHours = event.offset.totalDays * 24 + event.offset.hours;
                    $(this).html(event.strftime(totalHours + ':%M:%S'))
                }).on('update.countdown', function(event){
                    var format = '%H:%M:%S';
                    if(event.offset.minutes == 1 && event.offset.seconds==0){
                        alert(" You have only 1 minutes left");

                    }
                }).on('finish.countdown', function(){
                    alert("Reached Zero");
                });

               }

On button click.. pause function is called
 function pausetimer(){
            $('#clock').countdown('pause');
            //Here I need to get the countdown time here
            // Do I need to set flag here and how that flag would help me to get the time when countdown is paused?
        }

**Comment by hilios** [comment]
You need a logic 101 course!
