### ISSUE TITLE
I need to stop counter if network connection is lost

### ISSUE THREAD

**Issue by abiramasenthil** [hilios/jQuery.countdown#172]

**Comment by hilios** [comment]
Thatt is enough man, this is no place to learn javascript, THIS IS A PLACE to report **BUGS** and **ISSUES WITH THE PLUGIN**, your questions are easily solved by reading the documentation.
http://hilios.github.io/jQuery.countdown/documentation.html 

For now on I will close all your issues

**Comment by abiramasenthil** [comment]
Thanks for help.
