### ISSUE TITLE
Start date ---> "Server date" Setting..

### ISSUE THREAD

**Issue by nanse** [hilios/jQuery.countdown#174]
Hello~^^ My name is john~

I have a question~!
# I want to "start Date" Setting. <h1>

Please Help me~~^^

e.g 
```javascript
$('#clock').countdown(startDate, finalDate)
    .on('update.countdown', callback)
    .on('finish.countdown', callback);
```

**Comment by hilios** [comment]
This is a question or a feature request! If is a question the answer is NO the plugin does not work this way.

If it's a feature request, I am currently thinking in a way to accomplish that.

Regards
