### ISSUE TITLE
Upgrading NPM package

### ISSUE THREAD

**Issue by expert** [hilios/jQuery.countdown#176]
Hi, did you will push new version on NPM repository? 
How about include this config, in package.json : 
<code>
  "main": "src/countdown.js",
</code>

Because Webpack can't require it.

Thanks

**Comment by hilios** [comment]
:+1:

**Comment by jrobeson** [comment]
I don't see how the current package.json will even install, as it has a naming collision with another package

**Comment by bitfella** [comment]
Hello,
are you planning to release 2.1.0 on the NPM repository?
I can't require the package in Webpack, since the newest available version on NPM is 2.0.5.

Thanks

**Comment by hilios** [comment]
Added to `package.json` when version v2.2 gets ready I will push to NPM as well, thank you guys!
