### ISSUE TITLE
Countdown in minutes

### ISSUE THREAD

**Issue by aij** [hilios/jQuery.countdown#180]
Per the [documentation](http://hilios.github.io/jQuery.countdown/documentation.html#formatter) `%M` should print minutes left. Instead it prints `minutes % 60`, which of course is desirable when hours are also being printed, but not otherwise.

This is the workaround I'm using for now:

      $('.countdown').each(function(i, e) {
          var end_time = new Date(e.getAttribute('data-end-time'))
          var fmt = e.getAttribute('data-format')
          $(e).countdown(end_time, function(event) {
              // $(e).html(event.strftime('%M minute%!M'));
              var mins = Math.floor((event.finalDate.getTime() - Date.now()) / 60000)
              $(e).html(mins + ' minutes');
        });
      });

but of course it means I can't use your nice pluralization code.

We could do something like was done with daysToMonth, daysToWeek, and totalDays, but  I think a cleaner solution would be to look at what other fields are being shown in order to decide what modular arithmetic to perform. So, for example "%w weeks %H hours" would print the total number of weeks and hours mod 168. Of course that would not be completely backwards compatible, although I think it would work well for most uses.

**Comment by niknokseyer** [comment]
I would love to have this feature as well.

**Comment by hilios** [comment]
Thank you for your comments, but I think its worse to try find out what the user wants, I prefer the approach of empower then with the functionality.

That said I already added the `%N` directive to allow one to return the total count of minutes, as well the same for other time components.

**Comment by hilios** [comment]
I have updated the docs as well: http://hilios.github.io/jQuery.countdown/documentation.html#formatter

Please leave you thoughts.
