### ISSUE TITLE
odd issue with seconds being off by random intervals

### ISSUE THREAD

**Issue by robertminer1** [hilios/jQuery.countdown#184]
Let me start with giving you some sample code:

    $('#clock').each(function(){

    var $that = $(this);
    var finalDate;

    if($that.attr('data-countdown')) finalDate = $that.data('countdown');
    else finalDate = $that.text();
    var AdjDate = moment.tz(finalDate, "UTC").toDate();
    $that.countdown(AdjDate, function(event) {

        $that.html(event.strftime(''
            +' <div class="time-f">%-D<span>days</span></div>'
            +' <div class="time-f">%-H<span>h</span></div>'
            + ' <div class="time-f">%-M<span>m</span></div>'
            + ' <div class="time-f">%-S<span>s</span></div>'));
    });

    });

This should be pretty self explanatory, it just takes the time from a data attribute.  I'm loading both moment & jquery.countdown from a cdn.  If I open up different browsers on different computers, the time displayed in seconds could be off by a random interval ie sometimes, it's 20 seconds & other times it is 5 seconds & even up to 60 seconds off..  the display is just inconsistent.  Any advice?

**Comment by robertminer1** [comment]
Oh and the end time is always a static value taken from the database example:

2016-02-26 01:00:00
2016-02-20 01:15:00

**Comment by hilios** [comment]
Duplicated, let's track in the #177.
