### ISSUE TITLE
IE showing NAN, works fine on chrome

### ISSUE THREAD

**Issue by cinghaman** [hilios/jQuery.countdown#188]
This is how i am using it.
`
$('#clock').countdown('2016/03/16 07:00:00 +02:00', function(event) {
	   var $this = $(this).html(event.strftime(''
	     + '<div class="days" data-total="31" data-color="#f5bd15">DAYS<br/><span>%D</span></div>'
	     + '<div class="hours" data-total="24" data-color="#ed1c24">HOURS<br/><span>%H</span></div>'
	     + '<div class="minutes" data-total="60" data-color="#f5bd15">MINUTES<br/><span>%M</span></div>'
	     + '<div class="seconds" data-total="60" data-color="#ed1c24">SECONDS<br/><span>%S</span></div>'));
`

**Comment by hilios** [comment]
Sorry but the given date string won't parse to a date (this is an IE issue), use one of the following formats at [finalDate](http://hilios.github.io/jQuery.countdown/documentation.html#introduction).

If still need the timezone use the [MomentJS](http://hilios.github.io/jQuery.countdown/examples/timezone-aware.html) parser.

**Comment by cinghaman** [comment]
thanks for updated, ended up using additional countdown plugin just for IE
