### ISSUE TITLE
Conflict with nicescroll

### ISSUE THREAD

**Issue by Codevz** [hilios/jQuery.countdown#190]
Hi, 

First thanks for this script. Recently i found there is small conflict between Countdown and Nicescroll jquery script, With each countdown seconds, nicescroll trigger display block / none

You can check here: https://vid.me/2VB9

Is there any quick fix for this ?!

Thanks

**Comment by hilios** [comment]
Well the countdown script *does not* change any attribute of the element, in fact, you should do it, so clearly this **is not** an countdown issue!
