### ISSUE TITLE
flipping countdown

### ISSUE THREAD

**Issue by hariskhan10** [hilios/jQuery.countdown#191]
Dear Concern,

just like to ask you that how can I get the outlook of a flipping countdown which is used on http://hilios.github.io/jQuery.countdown/

there should be an example regarding that issue and please dont include template in a different script, try to include that in the same script of the countdown .. please

**Comment by hilios** [comment]
It is on Git:
https://github.com/hilios/jQuery.countdown/blob/gh-pages/_includes/main-example.html
