### ISSUE TITLE
event.lapsed event gets fired twice if finalDate is in the past

### ISSUE THREAD

**Issue by netpotential** [hilios/jQuery.countdown#193]
$('#countdown').countdown((moment.tz("2016/04/03 22:33:00").toDate(), function (event) {
            if (event.elapsed) {
                console.log(event.elapsed);
            }
});

When I use this code, for some reason event.lapsed fires twice. In the meantime I will find a way to handle it with an extra variable, but just thought I'd let you know (I'm using the latest version to this date).
Thanks!

**Comment by hilios** [comment]
It's because the legacy style binds all events with the same function. My suggestion is to use the callback style.
