### ISSUE TITLE
TypeError: instance is undefined

### ISSUE THREAD

**Issue by rahulteni** [hilios/jQuery.countdown#196]
Hi,
TypeError: instance is undefined	

instance.setFinalDate.call(instance, method);
I am getting above error in console when i added the code like 
$(document).ready(function() { 
    $("#getting-started").countdown("2016/10/10", function(event) {
     $(this).html(event.strftime('%D days %H:%M:%S'));	
  });
});   

can anyone help 
thanks in advance

**Comment by hilios** [comment]
Please be more descriptive, and even provide a JSFiddle with your problem, from the stack trace you described and your piece of code, I would infer that the problem is somewhere else.
