### ISSUE TITLE
How to make a countdown like 999 to 271 (current days remaining) as an animating entrance

### ISSUE THREAD

**Issue by Le-future** [hilios/jQuery.countdown#197]
Hi everyone,

I'm enjoying this awesome plugin and I have a request.

Example, the days remaining before the end date are 271 days.

I would like, when you open the page, the countdown starts from 999 and counting down in a few seconds to the current time remaining.

Do you think it's possible to do that?

Best regards

**Comment by hilios** [comment]
Yes it should. Make an animation in pure JavaScript and at the end of it start the countdown at the same element or in another.

**Comment by Le-future** [comment]
Hi, thanks for the response.

Honestly, I don't know how to do that :/

**Comment by hilios** [comment]
Sorry but I don have the time right now to assist you, since this question does not have any relation with the plugin itself, it would be suited for **Stackoverflow**. Try it the I believe that will be lots of people willing to help with your JS problem. 

Good luck.
