### ISSUE TITLE
Crashes on mobile when using multiple countdowns

### ISSUE THREAD

**Issue by alan-reed** [hilios/jQuery.countdown#202]
I have a page with 50+ countdowns on it. It works fine on desktop but crashes the android and iphone browsers. The page works on mobile if I use fewer countdowns. 

Besides the obvious answer of using fewer countdowns, is there a good solution to this problem?

**Comment by hilios** [comment]
The plugin it's optimized to use just one interval at time, so it doesn't seem to be a memory leak problem. I know that mobile platforms limits the JavaScript memory consumption for security reasons.

Probably not all you countdowns are shown at the same time, so you could start and stop them when they are shown at the screen.

Hope that helps!

**Comment by alan-reed** [comment]
Right now each of the 50+ countdowns tick 10 times a second. If I could change this to tick less often it may solve my problem.

Is there any way to change the tick interval?

**Comment by hilios** [comment]
@alan-reed yes there is the `precision` option: http://hilios.github.io/jQuery.countdown/documentation.html#configuration-object

**Comment by alan-reed** [comment]
Thank you!. This solved my problem.

---
Alan Reed
Founder, Proud Development, LLC

<https://www.prouddev.com>
