### ISSUE TITLE
UTC Timezone

### ISSUE THREAD

**Issue by D14RAP** [hilios/jQuery.countdown#205]
Currently i beleve the countdown uses the local timezone of the client, is it possible to overide this as the time i wish it to count down too is stored in a mysql database in UTC format, thanks

**Comment by hilios** [comment]
With aid of MomentJs its possible: http://hilios.github.io/jQuery.countdown/examples/timezone-aware.html

**Comment by karlingen** [comment]
As long as the input date is formatted in UTC you could simply do this: 

```
var dateTimeInUtc = Date.parse("2016-12-15 12:15:00Z");
$("#theCountdown").countdown(dateTimeInUtc, callback);
```
Note the added "Z" at the end of the datetime string.
