### ISSUE TITLE
Create Countdown from three seperate buttons. 

### ISSUE THREAD

**Issue by Jvittachi** [hilios/jQuery.countdown#207]
Hey, is there a way I can make a countdown start by clicking on a button?
So I'll be making three separate buttons - 20sec. 1:15 Minutes:Seconds and 3:00 Minutes.

**Comment by hilios** [comment]
Yes, check-it ou the Bootstrap example that does something very similar to what you described: http://hilios.github.io/jQuery.countdown/examples/bootstrap.html
