### ISSUE TITLE
Example issue

### ISSUE THREAD

**Issue by ProgrammerZ** [hilios/jQuery.countdown#211]
On page [Official example](http://hilios.github.io/jQuery.countdown/examples/advanced-coupon-site.html) there is an example that I used for countdown

it seems that this one:
```
if(event.offset.days > 0) {
    format = '%-d day%!d ' + format;
}
```

should be: 
```
if(event.offset.totalDays> 0) {
    format = '%-d day%!d ' + format;
}
```

had some issues with displaying days. Despite the fact that there were more than 4 days (with dateTime) at time of testing, the days sometimes did not display. And this change fixed the issue.

**Comment by hilios** [comment]
Tsk for the report!
