### ISSUE TITLE
Is there a way I can add centisecond next to the second

### ISSUE THREAD

**Issue by MLyte** [hilios/jQuery.countdown#216]
I want to add more result to the countdown, but I'm lame at jquery & stuff.

So basically I want it to look like : 
```
$('#clock').countdown('2016/09/07 20:00:00', function(event) {
              var $this = $(this).html(event.strftime(''
                + '<span>%D</span> j '
                + '<span>%H</span> h '
                + '<span>%M</span> m '
                + '<span>%S</span> s'));
                + '<span>%C</span> c'));
            });

```
Thank you

**Comment by hilios** [comment]
I believe that is easier to use the [`event.offset`](http://hilios.github.io/jQuery.countdown/documentation.html#event-object) rather than to hack the formatter.
