### ISSUE TITLE
Error : DateTime::__construct(): Failed to parse time string (09-14-2016) at position 0 (0): Unexpected character

### ISSUE THREAD

**Issue by Khal001** [hilios/jQuery.countdown#221]
Hi,

I was playing with the Joomla3.3 template setting, which use your countdown code. I don't remember what date I input. So my website was displaying the comingsoon.php with a count down of 145-days...
Afterward, I couldn't re-edit the template to remove the counter, until I deactivated a code line responsible for displaying the countdown in  comingsoon.php.
My site is working again, and can access to all my Joomla site admin, except editing the template parameters. I get the following error when attempting to EDIT the Templates Style:

An error has occurred.

    0 DateTime::__construct(): Failed to parse time string (09-14-2016) at position 0 (0): Unexpected character .

Any idea how to fix this mess?

I appreciate any help.

**Comment by hilios** [comment]
Sorry, but I don't know Joomla, or can give any advice on that matter. You should try to ask in a Joomla channel.
