### ISSUE TITLE
.countdown(timeout) not working in samsung galaxy S6 and Motorola G3

### ISSUE THREAD

**Issue by MRArguello** [hilios/jQuery.countdown#224]
Hey guys, I'm reporting this issue to see if its just my case, or if it's a known bug. I've been googling for a while and no one seems to have reported something of the sorts yet.

I'm programming a webapp for mobile devices. The idea is to have a screen that has a countdown to the date of the show the app is for, and from that day onwards, the app should skip that screen althogether and redirect to home.html.

I've programmed my countdown to do so, and I'm testing it right now with a 2s countdown. Seems to be redirecting properly in the many devices we've tried, but when run in a galaxy S6 or Motog3 the countdown works, but just stays at 0 without redirecting.

We think it might be some compatibility issue regarding the timeout function, since our app will run in the native browser of the phone and not in chrome or something else. We've had to solvw many compatibility issues with Js during this developement (such as "let" from js not being supported), and I thought maybe there was a workaround to fix this or any known information that could be of help.

I've pasted my code down here so you can check it, it might be that I'm writing something wrong. I'm using v2.2.0 of jquery.countdown.

Thanks a lot!

```
<div id="contador" class="counter">
</div>

	<script type="text/javascript">
		
		var timeout = new Date().getTime() + 2000;

		$('div#contador').countdown(timeout, function(event) { 

			var $this = $(this).html(event.strftime(''
				+ '<span>%D</span> D '
				+ '<span>%H</span> H '
				+ '<span>%M</span> M '
				+ '<span>%S</span> S'));
		})
		.on('finish.countdown', 
			function(){
				window.location.href= "templates/home.html"
			});
	</script>
```

**Comment by hilios** [comment]
Weird, I don't have any of these devices to test, but the scripts works fine in my Moto X 3gen and in a iPhone 6.

So probably it's an device problem, I heard about lagging when display multiples countdowns but nothing like that you describe. Can you provide some screenshots of the problem.

**Comment by MRArguello** [comment]
Well, we've been performing further testing and it ended up being something else related to the redirect we were supposed to do inside the .on(finish.countdown) and not the function itself (we've been having crazy bugs like that with different devices). 

I think I should just close or erase the thread, since it ended up not being related to the countdown.

Sorry, and  thanks a lot for your answer anyway!
