### ISSUE TITLE
Variable finalDate in Rails

### ISSUE THREAD

**Issue by ClementTANGUY** [hilios/jQuery.countdown#227]
Hi all, 
I have Company and Event models, a company CRUD many events thanks to one level nested resources. 
Each event has a date attribute, for example <%=@event.date%> is well displayed with a MM/DD/YYYY hh:mm:ss format.
Newbie, I would like to know how to call your countdown in the script, for each event CRUD by the companies, with this Ruby variable date as finalDate?
Thanks by advance.
Clem

**Comment by hilios** [comment]
Probably with the snnipet bellow, but much more a Rails question rather than here, as well check out the docs, it may help you a lot if you read it.

```js
$(el).countdown("<%=@event.date%>")
```

**Comment by ClementTANGUY** [comment]
Thanks!!!
