### ISSUE TITLE
TypeError: $(...).countdown is not a function

### ISSUE THREAD

**Issue by austd** [hilios/jQuery.countdown#23]
Hi, 

I was wondering if you could help me out, I'm a total jQuery rookie and I'm trying to figure out your jquery plugin. I keep on getting an error TypeError: $(...).countdown is not a function when trying to load your script. I'm just not sure what I'm doing wrong, but any help would be great! 

```
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>jQuery Final Countdown Timer</title>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
<script src="/jQuery.countdown-2.0.0/src/jquery.countdown.js" type="text/javascript"></script>
</head>


<body>
<div id="clock">Limited Time Only!</div>

<script type="text/javascript">
  $( document ).ready(function() {
      console.log( "ready!" );
         // 15 days from now!
        var date = new Date(new Date().valueOf() + 15 * 24 * 60 * 60 * 1000);
    $('#clock').countdown(date, function(event) {
        $(this).html(event.strftime('%D days %H:%M:%S'));
    });
 });
 </script>

</body>
</html>
```

**Comment by nabeelnazir** [comment]
@hilios i am facing same error , and can not get your above mention comment in more detail , what should I do to fix it ?

**Comment by hilios** [comment]
The browser couldn't find the `jquery.countdown` file, fix the load path at the `script` tag and everything should work properly.

**Comment by nabeelnazir** [comment]
@hilios I have included all necessary script tags, when i am using a simple asp.net empty web project countdown timer is working perfect, when i use this code in my desired project it keeps on giving me error in browser console and i am unable to see any count sown clock. Here is the code: 
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="~/Scripts/jquery.countdown.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        var endDate = "June 7, 2087 15:03:25";

        $('.countdown.simple').countdown({
            date: endDate
        });


    });

</script>

**Comment by nabeelnazir** [comment]
@hilios can you suggest some easy, simple count down clock code ?

**Comment by hilios** [comment]
Check-out our doc site: http://hilios.github.io/jQuery.countdown/examples/basic-coupon-site.html

**Comment by vochitan90** [comment]
<script type="text/javascript" src="http://cdn.rawgit.com/hilios/jQuery.countdown/2.1.0/dist/jquery.countdown.min.js"></script>

But not working, please help me for that, thanks.

**Comment by mbeara** [comment]
Don't know why but IT WORKS if you put all JS in the end of the file.. ?!!
Hope this helps :-)

**Comment by hilios** [comment]
Hello @mbeara, thank you for your help!

But because of the `$( document ).ready` this shouldn't be an issue, take for instance our doc site:
https://github.com/hilios/jQuery.countdown/blob/gh-pages/_layouts/main.html

The script tags are in the `head` tag, some of the script is not loading, should be very easy to identify in the Browser Developer Tools.

If the plugin itself was broken, it wouldn't work in any place.

Cheers!

**Comment by shipra18** [comment]
try using jQuery(document).ready(function($) {
//your stuff;
}

**Comment by jadeye** [comment]
`jQuery(document).ready(function($) {` resolved my issue as well...cheers :-)

**Comment by archit522** [comment]
My timer was working perfectly on development as well as production. But suddenly it started showing error on Heroku and timer is not working. 

`$clock.countdown is not a function. (In '$clock.countdown(futureDate, function(event) {
            $(this).html(event.strftime('%M:%S'));
          })', '$clock.countdown' is undefined)`

Can't figure out how to fix. Any help would be appreciated. Thanks :)

**Comment by vochitan90** [comment]
http://stackoverflow.com/questions/33592840/uncaught-typeerror-countdown-is-not-a-function-when-using-jcountdown
