### ISSUE TITLE
Uncaught TypeError: $(...).countdown is not a function(…)

### ISSUE THREAD

**Issue by jrean** [hilios/jQuery.countdown#239]
Hi,

I've read almost all posts related to this error but it still drives me nut.

My packages are concatenated with Gulp / Elixir (Laravel) in this order:

```
    // JS Front final file
    mix.scripts([
        'node_modules/jquery/dist/jquery.js',
        'node_modules/bootstrap-sass/assets/javascripts/bootstrap.js',
        'node_modules/jquery.countdown/jquery.countdown.js',
        'resources/assets/js/app.js'
    ], 'public/js/xxx.js', './');
```

`app.js` content is as follow:

```
jQuery(document).ready(function($){

    $('div#clock').countdown("2017/01/01", function(event) {
        $(this).text(
            event.strftime('%D days %H:%M:%S')
        );
    });

});
```

When I load the page I receive the following warning/error:

```
app.js:676Uncaught TypeError: $(...).countdown is not a function(…)
```

When I look at the concatenated `.js` file, `jquery.countdown` is right after `jquery` itself.

Can you please bring some light. What am I missing?

Thank you for the amazing package.

**Comment by jrean** [comment]
Hi, it will probably help someone.
I have been confused by the documentation from the website, saying:

```
bower install jquery.countdown
```

I was using `NPM`.

On github it says:

```
npm install --save jquery-countdown
```

With a dash (-) and not a dot (.).

It works properly now.

Thank you

**Comment by benIT** [comment]
thanks @jrean.
same problem with yarn.
Use `yarn add jquery-countdown` and don't use `yarn add `jquery.countdown`.
This dash/dot stuff makes me crazy.
