### ISSUE TITLE
countdown timer not runing multiple times

### ISSUE THREAD

**Issue by pwnchaurasia** [hilios/jQuery.countdown#299]
I need to re run the timer by getting the time from server.
when time reaches 0. 
`.on('finish.countdown', function(event){})` 

I am calling a function which uses ajax to get the data and I am updating the time.
It works perfectly fine for 2 times/ 3times. after that finish.countdown is not triggering.

Any solution for that ?

**Comment by webwamp** [comment]
hi @rjsnh1522  if you need server time to start counting, just passed time from server not all script, put server unixtime in variable or put server time in body attribute and in your countdown get that and add you needed time to this

AJAX called and fetch total script not good and made problems
