### ISSUE TITLE
Add exotic countdown examples

### ISSUE THREAD

**Issue by hilios** [hilios/jQuery.countdown#31]
Show off the plugin styling flexibility:

- [x] Flip numbers;
- [x] Timezone aware countdown;

**Comment by platypii** [comment]
+1 I wanted the flip-style clock, and wasted a bunch of time wondering why the library just outputs text. 

Am I missing something? It seems like there is no easy way to make jquery.countdown.js do what it says on the box. Very misleading, not a fan!!

**Comment by hilios** [comment]
@platypii you are not missing nothing, one of the project premisses is to be CSS agnostic, because I was tired of removing a bunch o unnecessary css files, and I hate when the JavaScript assumes that.

I just showcased the flip clock style in the examples, because the script supports as well, but is not the only style, I fell sorry if don't fit your time constrains requirements. I though I made very clear with the tag line:

```
A simple and html agnostic date countdown plugin for jQuery
```
http://hilios.github.io/jQuery.countdown/

**Comment by hilios** [comment]
Here is a full implementation of the countdown timezone aware using Moment JS:
http://hilios.github.io/jQuery.countdown/examples/timezone-aware.html
