### ISSUE TITLE
Is the countdown plugin comparing the client's timezone time with the finalDate?

### ISSUE THREAD

**Issue by techPackets** [hilios/jQuery.countdown#36]
The plugin method expects a finalDateTime to countdown to, so I am passing the time from the server as the final future time to the client. So does the plugin compares the server provided time with the client's local timezone time & starts the countdown?.

If so the functionality will run fine for a client in my timezone but not for the client is in some other timezone or in a daylight saving. Then I have to implement some other 
approach for time synchronization.

**Comment by hilios** [comment]
Here is a full implementation of the countdown timezone aware using Moment JS:
http://hilios.github.io/jQuery.countdown/examples/timezone-aware.html
