### ISSUE TITLE
counter

### ISSUE THREAD

**Issue by DomiBonza** [hilios/jQuery.countdown#39]
Hi, is there a way to make the plugin do a normal count instead of a count down?

**Comment by hilios** [comment]
Already implemented at master, the example bellow will count 5 sec from now and then start to count up:

```js
var fiveSecAgo = new Date().getTime() + 5000;
$dom.countdown(oneSecAgo, {elapse: true}).on('update.countdown', function(event) {
    if (event.elapsed) {
         event.strftime('%S passed from end');
    } else {
         event.strftime('%S till finish');
    }
});
```

**Comment by onskyD** [comment]
https://gist.github.com/onskyD/cc7547b8c536f58ea3e1d61ce6dadc2c#file-scripts-js
