### ISSUE TITLE
Countdown not working when both jQuery and Prototype JS are loaded

### ISSUE THREAD

**Issue by ronpeled** [hilios/jQuery.countdown#44]
The jQuery plugin is a great one. Thanks! I'm having some serious issues with it not working when I have Prototype JS loaded as well. I need to use this on a Magento site which require Prototype, typically this is not an issue since the .noConflict() resolves most issues. In this case, even using any known method of .noConflict() does not resolve the issue. 

It seems somewhere in the core of countdown.js the mechanism that updates the node gets overridden with Prototype.js and therefore leaves it empty at all times. I can give more details on the behaviour - but wasn't able to find where the actual issue is.

Thanks!

**Comment by stefkosmo** [comment]
How can I adapt this code to wrap the digits with html?
