### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by miguelhongo** [hilios/jQuery.countdown#5]
Hi Edson, I like your plugin a lot but I have a couple of questions. How can I translate to another language? I'm trying to figure it looking at the js but I'm lost. And if I want to use the basic style but I just want to display days instead of weeks what should I do?
Best reagards, thanks in advance.

**Comment by bosklapperbelg** [comment]
i want the countdown in dutch so how do i change Day%!d so i get 5 Dag**en** instead of 5 Day**s**
