### ISSUE TITLE
Looped counter 

### ISSUE THREAD

**Issue by olszak94** [hilios/jQuery.countdown#55]
``` javascript
var nextDay = new Date(). setHours(0, 0, 0, 0).getTime() + (1 * 24 * 60 * 60 * 1000);
$('#clock').countdown(nextDay, function(event) {
    $(this).html(event.strftime('%H hour%!H, %M min and %S sec.'));
});
```

that's the code i managed to put in my application.js file. It should count everyday 24 hours till 0, and then restart to 24 hours again (the loop), i can't make it work.

and below is the error i took from chrome console

``` javascript
Uncaught TypeError: undefined is not a function application.js:57
(anonymous function)
```

**Comment by dklimitless** [comment]
Hello 
I use this code:

```
var nextDay = new Date(). setHours(0, 0, 0, 0) + (1 * 24 * 60 * 60 * 1000);
$('#clock').countdown(nextDay, function(event) {
    $(this).html(event.strftime('%H hour%!H, %M min and %S sec.'));
});
```
But the countdown does not restart. Am I doing something wrong?

**Comment by yudiarnanda** [comment]
Hello,
How I can use this base on timezone?
`var nextDay = new Date(). setHours(0, 0, 0, 0) + (1 * 24 * 60 * 60 * 1000);
`
Try this `var nextYear = moment.tz("2018-30-12  00:00", "US/Central");` and working fine, not sure how to use on `var nextDay = new Date(). setHours(0, 0, 0, 0) + (1 * 24 * 60 * 60 * 1000)`;. 

Thanks for help,
Yudi
