### ISSUE TITLE
Timezone depending time

### ISSUE THREAD

**Issue by lOlbas** [hilios/jQuery.countdown#60]
My second question which i have to ask right after first one.
Is there a way to make this countdown be based on, for example GMT time, so that all clients will have same countdown time?

**Comment by travis-self** [comment]
Just to add to this, based on my testing the shortened format ('2014-08-14T00:00:00-0300') did not work in IE8. It would return 'NaN' in IE8 and below. The longer format did work ('Fri Aug 15 2014 14:00:00 GMT-0300 (BRT)').

**Comment by hilios** [comment]
Well this MUST be a problem with the IE8 date parser, since the plugin don't  perform the date parsing itself, and relies at the browser implementation.

**Comment by hilios** [comment]
Here is a full implementation of the countdown timezone aware using Moment JS:
http://hilios.github.io/jQuery.countdown/examples/timezone-aware.html
