### ISSUE TITLE
Resetting Countdown

### ISSUE THREAD

**Issue by andrewagga** [hilios/jQuery.countdown#62]
Dear Hilion,

i have a problem with the integrated apis.
"stop", "start", or any other method won't work in my project.

I tried to reset the timer via DOM -Manipulations with plain HTML and jQuery but nothing worked fine for me.

When i reset the timer, it overlays with the resetted time, and i get two different values, when i'm logging the value for the timer.

Do you have any ideas?

This is how i initialized it:

    var countwodnTimeFormatted = "2014/08/08 12:00:00"
    $('#timer').countdown(countdownTimeFormatted, function (event) {
                    self.timer.html(event.strftime('%H h %M m %S s'))
                })

Whether "stop", "pause" nor "start" or "resume" works.

Trying to act with the countdown in Chrome-console:
```javascript
$('#timer').countdown("stop")
[
<div id=​"timer" style=​"display:​ block;​">​01 h 59 m 54 s​</div>​
]
$('#timer').countdown("stop")
[
<div id=​"timer" style=​"display:​ block;​">​01 h 59 m 54 s​</div>​
]
$('#timer').countdown("stop")
[
<div id=​"timer" style=​"display:​ block;​">​01 h 59 m 54 s​</div>​
]
```
But the countdown still doesn't count - down.

**Comment by hilios** [comment]
I couldn't reproduce the issue reported, I uploaded a demo page at the docs to test this functionality and everything seems OK

http://hilios.github.io/jQuery.countdown/examples/bootstrap.html
