### ISSUE TITLE
Including bootstrap.js 3.2.0 breaks jquery.countdown

### ISSUE THREAD

**Issue by Greenek** [hilios/jQuery.countdown#66]
Hello there!

It seems that the problem with bootstrap.js (#2) has returned. After including both scripts countdown just stops working.

I'm using jQuery 2.1.1, bootstrap.js 3.2.0 and jQuery.countdown 2.0.4.

**Comment by stefkosmo** [comment]
Has their been a fix for this yet?

**Comment by hilios** [comment]
There is no issue with the `jQuery.countdown` plugin and Bootstrap > 3.2, I am uploading and example at the doc site.

Also I am untagging this as a bug a setting as support, since no bug was found!

**Comment by eebann** [comment]
my countdown stopped also with bootstrap

**Comment by hilios** [comment]
http://hilios.github.io/jQuery.countdown/examples/bootstrap.html
