### ISSUE TITLE
Countdown "flip" transition on your website

### ISSUE THREAD

**Issue by NomisGnos** [hilios/jQuery.countdown#72]
I'd submit a fix for you but you don't have this as part of your git project. This is only from your countdown flip action on your website: http://hilios.github.io/jQuery.countdown/ .  The transition flickers when you view it on Google Chrome and when you scroll down a little on the page.  This is because of the hardware acceleration not being used.  You can force it by adding this to your code:

.main-example * {-webkit-perspective: 1000;-webkit-backface-visibility: hidden; -webkit-transform: translateZ(0);-webkit-transform:translate3d(0,0,0); }

I noticed this when someone used your code on one of our website and saw that you had the same issue.  :)

**Comment by hilios** [comment]
Thank you by your comment, I added your suggestion to the css
