### ISSUE TITLE
Add "total amount of hours left" support

### ISSUE THREAD

**Issue by jlzi** [hilios/jQuery.countdown#75]
I would suggest to add possibility to display total amount of hours left (by analogy with total amount of days), something like this
```
hours: Math.floor(this.totalSecsLeft / 60 / 60) % 24,
totalHours: Math.floor(this.totalSecsLeft / 60 / 60),
```
, because sometimes it is useful.

**Comment by roboter** [comment]
Please add this feature, I put it on site and I needed, don't wont to look inside code of plugin, and did't find a method to create custom formatter.

**Comment by hilios** [comment]
C'mon @roboter the solution is written at the issue!!!!

```js
$('#clock').countdown(function(event) {
   var h = Math.floor(this.totalSecsLeft / 60 / 60) % 24;
   $(this).html( h + ' hours left...');
});
```

**Comment by roboter** [comment]
I think it will be easier to add format for TotalHours as ToltalDays have %D.
I did check the code and it is only 2 lines, I can even create a pull request :)

**Comment by hilios** [comment]
Ok, don't forget to add proper unit-tests and follow the code-style.
Regards!
