### ISSUE TITLE
Can't get days and months to output right countdown

### ISSUE THREAD

**Issue by Ravenna** [hilios/jQuery.countdown#76]
```js
$('#final-countdown').countdown('08/28/2015', function(event) {
   $(this).html(event.strftime('%m months %-d days %H hours '));
});
```

is how I am running it.  Seems easy enough.  Today (nov 6 2014), the countdown is 09 months 0 days 07 hours

Checking how many days till Aug 28th @ http://days.to/28-august/2015 shows 294 days. 

It should be outputting like 9 months 22 days and a few hours... 

Any ideas?

**Comment by emilsgulbis** [comment]
I had same issue, opened editor and tried to fix that.

Updated update() function, with
**days: Math.floor(this.totalSecsLeft / 60 / 60 / 24) - (30 * Math.floor(this.totalSecsLeft / 60 / 60 / 24 / 30))**
*days: totalDays - (30 * months)*

**Comment by hilios** [comment]
Please follow the discussion at #25 if you still are needing some help
