### ISSUE TITLE
Show more than 60 seconds.

### ISSUE THREAD

**Issue by tauchinleck** [hilios/jQuery.countdown#81]
Is it possible to show only seconds.  I don't want minutes, only to show '120 seconds' remaining.

**Comment by hilios** [comment]
Sure just sum all the outputs, like this example: http://hilios.github.io/jQuery.countdown/examples/show-total-hours.html

```js
$('#clock').countdown("2020/10/10", function(event) {
  var totalSeconds = event.offset.totalDays * 24 * 60 * 60
    + event.offset.hours * 60 * 60
    + event.offset.minutes * 60
    + event.offset.seconds;
  $(this).html(totalSeconds + ' seconds');
});
```

I didn't test this script so it can have some typo.
