### ISSUE TITLE
Functionality tests fail on windows 7.

### ISSUE THREAD

**Issue by konstantin-popov** [hilios/jQuery.countdown#83]
I ran ```grunt test``` on Windows 7 x64 and 3 tests failed ("Functionality stop/start the countdown", "Functionality pause/resume the countdown", "Functionality control of a single instance correctly").
The way to make them pass is to change the waiting time from 510ms to 550. Not sure but looks like something is delaying the real start of the countdown after the call for more than 10ms.

**Comment by hilios** [comment]
@FagnerMartinsBrack I update all tests to use sinon fake timers, and they are :rocket: !!!!

**Comment by FagnerMartinsBrack** [comment]
:tada:
