### ISSUE TITLE
Countdown issue when user change his machine date

### ISSUE THREAD

**Issue by torunarucho** [hilios/jQuery.countdown#84]
Dear Hilios,

I've read the issue regarding countdown problem published in link below : 
https://github.com/hilios/jQuery.countdown/issues/26

It's marked closed, but I don't see any workaround to set the countdown time according the GMT, since the countdown will always change when the user change his machine time & date.
We need it to detect the user's timezone and use it as the current time & date, so the countdown won't be changed in case the user change his machine date (unless he change the timezone).
Or can you advise on how to combine the countdown script with : http://momentjs.com/timezone/ ?

We've tried to add validation from the server-side, but of course it doesn't change on how the countdown presented in the client-side.

Could you give any advise?

Regards,
Robert

**Comment by hilios** [comment]
Well Robert, this is a well know use case and it's a very hard computational problem, and even you use MomentJS to mitigate, still it's not a perfect solution.

I'm still pending an timezone example using MomentJS, sorry if I could have the time to accomplish this task yet.

**Comment by adanarchila** [comment]
I had the same problem and one of the solutions I found wasn't working on Safari Mobile, so the first thing you need to do is convert your final date in UTC so the time I needed was January 27, 2015 00:00:00 so that date in UTC it will be January 27, 2015 05:00:00 and then pass that object date to the plugin, and it should work fine. 

```
var date = new Date('1/27/2015 05:00:00 UTC');
$('#countdown').countdown(date);
```

**Comment by hilios** [comment]
Here is a full implementation of the countdown timezone aware using Moment JS:
http://hilios.github.io/jQuery.countdown/examples/timezone-aware.html

**Comment by torunarucho** [comment]
Thanks man.. :) 


     On Tuesday, July 14, 2015 4:20 AM, Edson Hilios <notifications@github.com> wrote:
   

 Here is a full implementation of the countdown timezone aware using Moment JS:
http://hilios.github.io/jQuery.countdown/examples/timezone-aware.html—

**Comment by sagarrakshe** [comment]
@hilios 
I was able to set timer irrespective of the local time, but the problem I am facing is, when the local time is changed, the countdown timer changes. 

Even in this link http://hilios.github.io/jQuery.countdown/examples/timezone-aware.html if you change the local machine time, the countdown changes. Any solution for this use case?

**Comment by hilios** [comment]
@sagarrakshe well this is a "issue" of the JavaScript implementation itself

> The JavaScript Date object supports a number of UTC (universal) methods, as well as local time methods. UTC, also known as Greenwich Mean Time (GMT), refers to the time as set by the World Time Standard. The local time is the time known to the computer where JavaScript is executed.
>
> – From: Mozilla Developer Network

Unfortunatly it is not a simple issue to handle because the countdown use the machine date to subtract from the final date.

I am now thinking how to implement that in a way that is compatible with the current implementation

**Comment by h-morales** [comment]
Why not add start date option to override default starting date?

**Comment by phildkevin** [comment]
Does it have any solution today?
It has a huge effect on the countdown every time I change my local machine time.
