### ISSUE TITLE
Adivce to install

### ISSUE THREAD

**Issue by michal222** [hilios/jQuery.countdown#85]
Hello, please advice, I can not run jQuery.countdown according to the instructions, do you have another example of a file or somewhere to download?
Thank you

**Comment by hilios** [comment]
It's impossible to guess what kind of trouble you are going through, but as a default the plugin works well, issues with the install are often cause by bad understanding of javascript or the user own HTML and JS.

You can always checkout the docs: http://hilios.github.io/jQuery.countdown/documentation.html

There are plenty of examples there, if not works at all please try to be more descriptive about your problem.
