### ISSUE TITLE
Wrap Digits

### ISSUE THREAD

**Issue by picard102** [hilios/jQuery.countdown#86]
Is it possible to wrap each individual digit with a span?

**Comment by hilios** [comment]
Yup, check-out this example: http://hilios.github.io/jQuery.countdown/examples/website-launch.html

```js
$('#clock').countdown('2020/10/10').on('update.countdown', function(event) {
  var $this = $(this).html(event.strftime(''
    + '<span>%-w</span> week%!w '
    + '<span>%-d</span> day%!d '
    + '<span>%H</span> hr '
    + '<span>%M</span> min '
    + '<span>%S</span> sec'));
});
```

**Comment by gettonet** [comment]
@hilios, not like that, I think @picard102 needs, for example DD-HH-MM to be:
`<span>D</span><span>D</span>-<span>H</span><span>H</span>-<span>M</span><span>M</span>`

Is there a quick/light way to achieve this?
