### ISSUE TITLE
Shortcode button

### ISSUE THREAD

**Issue by michal222** [hilios/jQuery.countdown#88]
I would like to insert shortcode manually button with my text, countdown works
[couponCountdown time=''  '<button type="button" class="btn">My text</button>']
Html result
http://jsfiddle.net/michal77/gyjtjms0/
Thanks

**Comment by hilios** [comment]
I am not sure if I understand you but I updated your JSFiddle:
http://jsfiddle.net/gyjtjms0/2/

**Comment by dingo-d** [comment]
Shortcodes are used in wordpress. This plugin is just a plugin. You need to create the shortcode yourself.

**Comment by hilios** [comment]
:+1:
