### ISSUE TITLE
Instant rendering despite lower interval

### ISSUE THREAD

**Issue by wrthwhl** [hilios/jQuery.countdown#90]
Hi

First off thank you very much for the great plugin and the very thorough implementation. 

I'd like to use your plugin to show the countdown to a specific date in weeks and days only. Now because of the low level of detail I wanted to set a lower interval but it seems that the clock only get's rendered after the interval has expired a first time. Now I was hoping you could give me a hint as to how I can use your plugin with a lower interval while making sure the clock is rendered instantaneously. 

Many kind thanks in advance for your help
Marco

**Comment by hilios** [comment]
Hello there, to be short the exact line you seek is this one:
https://github.com/hilios/jQuery.countdown/blob/master/src/countdown.js#L13

But the countdown is rendered right away when the script is started:
https://github.com/hilios/jQuery.countdown/blob/master/src/countdown.js#L150

Let me know if this work for you!
