### ISSUE TITLE
How to use the countdown plugin.

### ISSUE THREAD

**Issue by ubilli** [hilios/jQuery.countdown#91]
please how do i use your countdown because it is not working. this is my code.
`<div id="getting-started"></div>`
`<script type="text/javascript">
    	$("#getting-started").countdown("2015/01/01", function(event) {
    		$(this).text(
    			event.strftime('%D days %H:%M:%S')
    			);
    	});
    </script>`
this is the output of the code.
`00 days 00:00:00`
please what can i do to it? Gues.

**Comment by hilios** [comment]
Well, will be very hard to me guess what the problem is with so little info. If you can push some html online would be easier.

You can checkout the examples, they are working:
http://hilios.github.io/jQuery.countdown/examples/basic-coupon-site.html
