### ISSUE TITLE
Anyone seeing odd display issues?

### ISSUE THREAD

**Issue by MichaelTurk** [hilios/jQuery.countdown#93]
Have the countdown running on a site and two users have had issues with scrolling where their entire screen or half of their screen will blink black when the seconds tick. Have not been able to reproduce it on any browser/OS combo, so I am thinking it is likely an LCD display or graphic chipset problem. However, there is no common element. 

Anyone else seen/heard anything like this?

**Comment by dingo-d** [comment]
Do you mean  #72 issue?

**Comment by MichaelTurk** [comment]
Thanks. I missed that when I searched the issues. I'm not sure it's the same problem, but we'll try it out. Closing this thread in the meantime.
