### ISSUE TITLE
support zepto?

### ISSUE THREAD

**Issue by atian25** [hilios/jQuery.countdown#94]
had try but can't trigger event callback

**Comment by hilios** [comment]
Never tried before! Provide a JSFiddle and let's make it work

**Comment by hilios** [comment]
Sorry I tried, but I use a jQuery functionality (`_data` property to find attached events) that it's not available at Zepto. So it's incopatible!

**Comment by FagnerMartinsBrack** [comment]
@hilios isn't that an undocumented functionality? jQuery team remove undocumented features very often, that could break the plugin usage in the wild.
