### ISSUE TITLE
Event when "finish.countdown"

### ISSUE THREAD

**Issue by ljungstrom** [hilios/jQuery.countdown#95]
Hi
Great plugin, but I can't get the .on("finish.countdown", function(event) { working in the "Multiple instances on the same page" example. Is there a way to have a finish event on each of the counters?

Cheers
Björn

**Comment by dingo-d** [comment]
Have you tried targeting the countdown element wrapper and adding .each(function{}); and then in the each use $(this).on("finish.countdown"...) (or jQuery(this) if you didn't replace it with $).

**Comment by ljungstrom** [comment]
Hi
I have tried that, code below. But it triggers console.log several times :-O.


$("[data-countdown]").each(function() {
   var $this = $(this), finalDate = $(this).data("countdown");

   $this.countdown(finalDate, function(event) {
     $this.html(event.strftime("%D days %H:%M:%S"));
     $this.on("finish.countdown", function(event) {
    console.log("foo");
    });
    });
   });
