### ISSUE TITLE
Showing non-zero values (days)

### ISSUE THREAD

**Issue by rdudacz** [hilios/jQuery.countdown#96]
Hello guys,

first of all, thank you for this great library!
I am using it in the format
```javascript
	$('[data-countdown]').each(function() {
	    var $this = $(this), finalDate = $(this).data('countdown');
	    $this.countdown(finalDate, function(event) {
			$this.html(event.strftime('%D days %H:%M:%S'));
	   }
	});
```

This works well, however - the output is in this format: `00 days 04:35:20`.

I am trying to modify the way the output would be like 
`04:35:20`
or in case the count of days is greater than 0, then:
`1 day 04:35:20` or `2 days 04:35:20`.

How to set this kind of formatting when is used multiple instances of `.countdown` on one page?

Thank you.

**Comment by hilios** [comment]
Hi, the trick here is to use the [event object](http://hilios.github.io/jQuery.countdown/documentation.html#event-object) properties to build the output format according the way you want, like [this example](http://hilios.github.io/jQuery.countdown/examples/advanced-coupon-site.html).

```js
$this.countdown(finalDate, function(event) {
    var format = '%H:%M:%S';
      if(event.offset.days > 0) {
        format = '%-d day%!d ' + format;
      }
      if(event.offset.weeks > 0) {
        format = '%-w week%!w ' + format;
      }
     $this.html(event.strftime(format));
}
```
