### ISSUE TITLE
Feature Request - Count Up

### ISSUE THREAD

**Issue by Zammalad** [hilios/jQuery.countdown#97]
This was a perfect solution for what I was trying to achieve in my project. However, the only functionality which it is missing for me is the ability to countdown past the end time. Example I have a monitoring system and I wish to see how long over the end time it is i.e a count up.

**Comment by FagnerMartinsBrack** [comment]
https://github.com/hilios/jQuery.countdown/issues/39

**Comment by hilios** [comment]
:+1:
