### ISSUE TITLE
Year/day/hours can't calculate corectly

### ISSUE THREAD

**Issue by mr-zenith** [hilios/jQuery.countdown#98]
I use this plugin and when i formated in '%Y %D %H' it calculate 01 year - 670 days and 12 hours.
but All of us know 670 days can be 2year

<script>
    $(document).ready(function () {
        $('#time').countdown('@ViewBag.compitationdata', function (event) {
            $(this).text(event.strftime('%Y %D %H'));
        });
    });
</script>

**Comment by BraadMartin** [comment]
You can use a lowercase d instead of uppercase D to get the number of days minus any full years/weeks.

http://hilios.github.io/jQuery.countdown/documentation.html

**Comment by hilios** [comment]
To be more specific check-out the [event formatter section at the docs](http://hilios.github.io/jQuery.countdown/documentation.html#formatter).
