### ISSUE TITLE
Backbone agnostic countdown flip example

### ISSUE THREAD

**Issue by lightonphiri** [hilios/jQuery.countdown#99]
Thank you for the plugin---quite useful.

I am trying to follow through your implementation of the countdown flip example on the main page [1] and was able to dig and figure out that it is implemented using lodash.js? I wonder, would it be possible for you to help with a pure JavaScript implementation of this? I know ZERO lodash.js and figured you might help me save some time :)

[1] https://github.com/hilios/jQuery.countdown/blob/gh-pages/_includes/main-example.html

**Comment by hilios** [comment]
Lodash is used only to generate the template (and you can you any lib you prefer), the rest is straight forward javascript, don't be lazy :wink: isn't a enormous source code.

```js
// L20: template = _.template($('#main-example-template').html()),
template = function(variables) {
   var html = $('#main-example-template').html();
   for (var name in variables) {
      if (!variables.hasOwnProperty(name)) continue;
      // Replace the variables at the html
      html = html.replace(new Regexp("<%= " + name + " %>", variables[name])
      // Not good idea though because don't escape html....
   }
}
// L74: _.delay =>
setTimeout(function($node) {
   $node.addClass('flip');
}, 50, $node);
```

**Comment by lightonphiri** [comment]
Thank you for this. I was trying to be lazy when I asked for this :) I actually got it to work soon after I asked. Thank you again.
